name: Front CI/CD Workflow
on: 
  push:
    branches: 
      - develop
    paths:
      - 'front/**'
  pull_request:
    branches: 
      - main
    paths:
      - 'front/**'

jobs:
   build-and-test-front-with-coverage:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node for Web project
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: front/package-lock.json
    - name: Install dependencies for front project
      run: npm ci
      working-directory: front
      
    - name: Build front project
      run: npm run build --if-present
      working-directory: front
 
    - name: Run test with coverage
      working-directory: front
      run: npm run test -- --code-coverage --browsers=ChromeHeadless --watch=false
      
    - name: Commit Coverage Report
      run: |
        git config --global user.email "mihai.cojusnean@gmail.com"
        git config --global user.name "GitHub Actions"
        git fetch --all
        git checkout coverage-reports
        git pull origin coverage-reports
        mkdir -p coverage-repport/front
        cp -r front/coverage/bobapp/* ./coverage-repport/front
        git add ./coverage-repport/front
        git commit -m "Update Coverage Reports"
        git push origin coverage-reports
    env:
     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     
   sonar-scan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - 
        name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - 
        name: Install dependencies
        working-directory: front
        run: npm ci
      - 
        name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - 
        name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONT }}
        with:
          projectBaseDir: front
          args: >
            -Dsonar.projectKey=mihai-cojusnean_ci-cd-openclassroom-front
            -Dsonar.organization=mihai-cojusnean
