name: Front CI/CD Workflow
on: 
  push:
    branches: 
      - develop
    paths:
      - 'front/**'
  pull_request:
    branches: 
      - main
    paths:
      - 'front/**'

jobs:
   build-and-test-front-with-coverage:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node for Web project
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: front/package-lock.json
    - name: Install dependencies for front project
      run: npm ci
      working-directory: front
      
    - name: Build front project
      run: npm run build --if-present
      working-directory: front
 
    - name: Run test with coverage
      working-directory: front
      run: npm run test -- --code-coverage --browsers=ChromeHeadless --watch=false
      
    - name: Commit Coverage Report
      run: |
        git config --global user.email "mihai.cojusnean@gmail.com"
        git config --global user.name "GitHub Actions"
        git fetch --all
        git checkout coverage-reports
        git pull origin coverage-reports
        mkdir -p coverage-repport/front
        cp -r front/coverage/bobapp/* ./coverage-repport/front
        git add ./coverage-repport/front
        git commit -m "Update Coverage Reports"
        git push origin coverage-reports
    env:
     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   sonarqube_scan:
    name: Run SonarQube Scanner
    needs: build-and-test-front-with-coverage
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Setup Node for Web project
        uses: actions/setup-node@v4
        with:
         node-version: '20'
      - name: Set Sonar Scanner Home
        run: |
          echo "SONAR_SCANNER_HOME=C:/sonar/native-sonar-scanner/sonar-scanner-5.0.1.3006-windows" >> $GITHUB_ENV
          echo "C:/sonar/native-sonar-scanner/sonar-scanner-5.0.1.3006-windows/bin" >> $GITHUB_PATH
      - name: Verify Sonar Scanner Installation
        run: |
          echo "Verifying Sonar Scanner installation..."
          sonar-scanner -v    
      - name: Run SonarQube Scanner
        run: |
          sonar-scanner
        working-directory: front
        env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONT }}
           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
           
