name: Front CI/CD Workflow
on: 
  push:
    branches: 
      - develop
    paths:
      - 'front/**'
  pull_request:
    branches: 
      - main
    paths:
      - 'front/**'

jobs:
   build-and-test-front-with-coverage:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node for Web project
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: front/package-lock.json
    - name: Install dependencies for front project
      run: npm ci
      working-directory: front
      
    - name: Build front project
      run: npm run build --if-present
      working-directory: front
 
    - name: Run test with coverage
      working-directory: front
      run: npm run test -- --code-coverage --browsers=ChromeHeadless --watch=false
      
    - name: Commit Coverage Report
      run: |
        git config --global user.email "mihai.cojusnean@gmail.com"
        git config --global user.name "GitHub Actions"
        git fetch --all
        git checkout coverage-reports
        git pull origin coverage-reports
        mkdir -p coverage-repport/front
        cp -r front/coverage/bobapp/* ./coverage-repport/front
        git add ./coverage-repport/front
        git commit -m "Update Coverage Reports"
        git push origin coverage-reports
    env:
     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     
   sonar-scan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm install

      - name: Run Jasmine tests and generate report
        run: npm run test -- --no-watch --code-coverage

      - name: Publish Jasmine
        uses: actions/upload-artifact@v4
        with:
          name: jasmine-report
          path: front/coverage/bobapp/*

      - name: install scanner
        run: npm install -g sonarqube-scanner

      - name: run sonar scanner
        run: sonar-scanner -Dsonar.token=${{secrets.SONAR_TOKEN_FRONT}}
           
